### ISSUE TITLE
Notes & Questions

### ISSUE THREAD

**Issue by wadetandy** [wagenet/graphiti-rails#5]
Wanted a place to capture random thoughts while looking over the code and also a place to address questions you ask in your comments.

**Comment by wadetandy** [comment]
> https://github.com/wagenet/graphiti-rails/blob/master/lib/graphiti/rails/exceptions_app.rb#L22-L23
> Do we actually want to log?

This probably should depend on the specific error type?  If the response is >=500, I'd think logging is appropriate.  If it's something like a 400 bad request that we have gotten from our request validator, then logging is probably not necessary.

**Comment by wadetandy** [comment]
> https://github.com/wagenet/graphiti-rails/blob/master/lib/graphiti/rails/context.rb#L5-L10
> Any downside to including this in all Rails controllers?

Would follow the lead of some other projects and have this as a configurable option:

```ruby
Graphiti::Rails.configure do |c|
  c.base_controller = 'ApplicationController'
end
```

**Comment by wadetandy** [comment]
The list of errors you pulled from graphiti to merge into `action_dispatch.rescue_reponses` doesn't include the new [`InvalidRequest`](https://github.com/graphiti-api/graphiti/blob/master/lib/graphiti/errors.rb#L755-L769) error, which will be one of the critical ones we need to handle.

**Comment by richmolj** [comment]
I wrote my own notes here: https://gist.github.com/richmolj/ded6c99353ead759785caaeeb68a7e60

To touch on a few things Wade mentioned:

>  If the response is >=500, I'd think logging is appropriate. If it's something like a 400 bad request that we have gotten from our request validator, then logging is probably not necessary.

I think these are good defaults, we just need the ability to override with `register_graphiti_exception FooError, log: false`. One example is avoiding logging on 404 - maybe, maybe not. I think we have a few internal BGov errors as well were we just want to eliminate legacy noise.

> Would follow the lead of some other projects and have this as a configurable option:

I'd prefer including a mixin as a little more explicit. The downside to applying to all controllers is running AMS/whatever and graphiti side-by-side.

**Comment by wagenet** [comment]
@wadetandy for now, I think we'll only log fatal exceptions. See eeb6b6d.

**Comment by wagenet** [comment]
See also #7

**Comment by wagenet** [comment]
For easier discussion, I've split these up into multiple issues. If I missed anything, please open a new issue.
