### ISSUE TITLE
Decide if auto-include is correct

### ISSUE THREAD

**Issue by wagenet** [wagenet/graphiti-rails#7]
Right now we're auto-including Graphiti code in `ActionController::Base` [source](https://github.com/wagenet/graphiti-rails/blob/eeb6b6d91e2739a7d324205bba6975b52a668109/lib/graphiti/rails.rb#L65-L69). This may be too aggressive.

First question is whether this has any potential downsides. If so, we should definitely let it be at least configurable. My inclination is to leave it for now and have us be less aggressive if people report issues.

**Comment by wagenet** [comment]
See also https://github.com/wagenet/graphiti-rails/issues/5#issuecomment-488724054 and https://github.com/wagenet/graphiti-rails/issues/5#issuecomment-488733910

**Comment by richmolj** [comment]
Mixin vs Railtie relevant to this one: https://github.com/wagenet/graphiti-rails/issues/10#issuecomment-490908327

**Comment by wagenet** [comment]
I think with rescue_registry (#22) this is fine.
